---
basePath: "/v1"
definitions:
  ContactAllocataire:
    properties:
      nir:
        description: NIR de l'allocataire (sur 13 chiffres)
        pattern: "^[0-9]{13}$"
        type: string
        example: 1234567890123
      matricule:
        description: N° de dossier famille à la Msa ou à la Caf
        example: "000012300000000"
        type: string
      prenom:
        description: Prénom
        example: Camille
        type: string
      nom:
        description: Nom
        example: Dupont
        type: string
      rolepers:
        description: |
          Rôle de l'individu dans le dossier
          - DEM si la personne est le demandeur du rSA
          - CJT si la personne est le conjoint du demandeur
          - ENF si la personne est un enfant
          - AUT si la personne est une autre personne
          - RDO si la personne est le responsable du dossier et que cette personne n'est pas présente sur le dossier"
        example: DEM
        type: string
        enum:
          - DEM
          - CJT
          - ENF
          - AUT
          - RDO
      civilite:
        description: Civilité de la personne
        example: MONSIEUR
        type: string
        enum:
          - MONSIEUR
          - MADAME
      numdemrsa:
        description: Numéro de la demande de rSA
        example: 01234567890
        type: string
      dtdemrsa:
        description: Date de la demande de rSA
        example: "2018-08-06"
        type: string
      dtsoumded:
        description: Date à partir de laquelle la personne est soumises aux droits et devoirs
        example: "2018-08-06"
        type: string
      numteldo:
        description: Numéro de téléphone affecté à la personne
        example: "0556894472"
        type: string
      numtel2do:
        description: Second numéro de téléphone affecté à la personne
        example: "0630080982"
        type: string
      emaildos:
        description: Adresse email affectée à la personne
        example: camille.dupont@example.com
        type: string
    type: object
host: api.cnaf.example.com
info:
  description: "Ce fichier contient une proposition pour une API mise à disposition par la CNAF pour
  permettre la récupération des coordonnées de contact des bénéficiaires."
  title: Proposition d'API pour la récupération des données de contact
  version: 0.0.1
paths:
  "/allocataire/{NIR}/coordonneesContact":
    get:
      description: Obtenir les informations de contact pour une personne
      parameters:
      - description: NIR de l'allocataire (sur 13 chiffres, sans la clé)
        pattern: "^[0-9]{13}$"
        type: string
        in: path
        name: NIR
        required: true
      produces:
      - application/json
      responses:
        '200':
          description: requête réussie
          schema:
            "$ref": "#/definitions/ContactAllocataire"
        '404':
          description: Allocataire introuvable
      summary: Obtenir les informations de contact pour une personne
schemes:
- https
swagger: '2.0'
